language: node_js
node_js:
- node
before_script:
- openssl des3 -d -A -in encrypted/cf.enc -k "$SSL_PASSWORD" > src/config.json
script:
- yarn test:cov
env:
  global:
    secure: kxIxGTG+sNIXlK/5fgc+O4lLX2JaKBtAfyjbaomTbxoAg7PxzTQ/gofPQI8wCBs+hMQwoldsWYRByzzuLUzyd9HU7eoWtU5NuxvkM3QXQNVIA65paaHJQuFW8UF701Wh3qUeTueFjs3TT+hzs41KR3gK5oH2QwAUCFrmoH6lB5X0GoZuQ/4qJCkDTMa8ed5GBhGvG5wZOJr/qIWW4hU6a4qfuWgQ9wXDnCn7gROwtaU2SWBkGAb/qjglumq5yitKh0Eoyo+k1eyNvMGnT5Y3c96I1PbNvaDJrMXPaOAEDiqQ8Sqeq3l8w/LwgxXucCYgFFURqIkshJcbMp/fHlhyWIm2sM9d7AnmCZEN3JUFShqEoC1Uqg0Cxiay0LCUxGCNcBpY2crfWGRE/8dJ9sw94QMqljSlOLxLtIjt5gzK4fnJj7ky+fIxFGELktJYdsTpwtCA7x054TUsmFrs1+yy0k5RoAsdlzRU8IKSKcvNe3rDCru0qYN0njHTUhHsHtPf7yfEb9WgcD6jnCg82aexcpJpSP7nDNEBs4NoX7+kCn3XEvdF8mgG/JqKZJ76LuhEzhIi4b/a2lJ+te1m/6L4NAV+MwtWjAH5iOlkWUH2gGei3XM2lygyPPCkHnK2jvrbAv4XaCBio96rs/cOeI2Xo4tn4CHLZE2QlQRvXx4HEac=
